[project]
name = "cone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "auto-py-to-exe>=2.48.1",
    "opencv-python>=4.12.0.88",
    "pillow>=12.0.0",
    "requests>=2.32.5",
]
